### ISSUE TITLE
Failing to parse int flag

### ISSUE THREAD

**Issue by olafurpg** [scalameta/moped#19]
**Describe the bug**

**To Reproduce** Steps to reproduce the behavior:

Define a command with an Int field `port`
```scala
case class PackageServer(
    store: PackageStore = new InMemoryPackageStore,
    port: Int = 8080,
```
Run the command with a custom port argument

```
[info] running (fork) com.sourcegraph.package_server.PackageServer --port 4040
[info] error: Type mismatch at '.port';
[info]   found    : String
[info]   expected : Int
```

**Expected behavior**

It parses the port as 4040 instead of reporting an error.

**Comment by 2m** [comment]
Would it be possible to get a release with this fix?

**Comment by olafurpg** [comment]
Whoops, I thought I had already released this. Just hit on the same bug myself recently and was confused because I assumed I had already upgraded. I kickstarted a 0.1.11 release and if the artifacts should become available on Maven Central if everything goes well
